! my_project
  | -settings
  |--|--__init__.py
  |--|--dev.py
  |--|--prod.py
  | -mainapp
  |--|--__init__.py
  |--|--moduls.py
  |--|--veiws.py
  |--| -templates
  |--|--| -mainapp
  |--|--|--|--base.html
  |--|--|--|--index.html
  | -authapp
  |--|--__init__.py
  |--|--moduls.py
  |--|--veiws.py
  |--| -templates
  |--|--| -authapp
  |--|--|--|--base.html
  |--|--|--|--index.html
